### PR TITLE
chore[hosting]: use docker for hosting

### PR DESCRIPTION
**Pull request by onerandomusername**
Now that we have a dockerfile, one of our supported hosting platforms will use that file for running the bot, and will ignore the Procfile. This means that we can switch the process type back to worker, which is what our other supported hosting platform is expecting.

### CODE REVIEW

**Comment by bast0006** [comment]
@onerandomusername have you tested this on our providers?

**Comment by onerandomusername** [comment]
Yes, this resets it to what it was in commit ff75614c8eca3988a37431fd492f6a1712ed2666

**Comment by bast0006** [comment]
Ok

**Review by bast0006 — APPROVED** [review]

**Comment by onerandomusername** [comment]
We *could* add a [heroku.yml](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#heroku-yml-overview) file in order to build a docker container on heroku as well. Perhaps we should do that, which would hopefully let us remove requirements.txt in a future pr, provided every integration works after this is merged.

**Comment by onerandomusername** [comment]
I've managed to set up a heroku.yml file, which now means that heroku will deploy by creating a docker image,
however, I had to run `heroku stack:set container` on the application, so I ended up making an app.json file.

This needs to be tested by deploying to heroku.

**Comment by onerandomusername** [comment]
Testing if I can make this project deploy, and then we should be good to go.

**Review by dawnofmidnight — APPROVED** [review]
I cannot deploy to Heroku at the moment, but everything looks good.

**Pull request merged**
