### PR TITLE
Use two lines after all imports instead of 1 line

### PR DESCRIPTION
**Pull request by onerandomusername**

### CODE REVIEW

**Comment by Shivansh-007** [comment]
Changelog this.

**Comment by onerandomusername** [comment]
Not worth a changelog, none of this is user facing.

**Comment by bast0006** [comment]
Honestly, we should still changelog this, if only for ourselves

**Review by bast0006 — APPROVED** [review]
Alright... but this is gonna really shake things up a bit. Not sure how the final merge is going to be, but hopefully not too bad for all the other prs.

**Pull request merged**
